services:
  - type: web
    name: yume
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
