services:
  - type: web
    name: yume
    env: node
    region: oregon
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/auth/status
    envVars:
      - key: DATABASE_URL
        value: "postgresql://postgres:NpG_F%3F%2FBQWuK8U%23@db.fkfcjttsdayflggazgrc.supabase.co:5432/postgres"
